---
title: "Getting and Cleaning Data Course Project"
author: "Javier Chang"
date: "19/4/2020"
output: md_document
---

## About the project

This is the final project of the course **Getting and Cleaning Data** to demonstrate our ability to collect, work with, and clean a data set. The goal is to prepare a tidy data that can be used for later analysis.

### Raw data

The raw data comes from the accelerometers from Samsung Galaxy S smartphones used in an experiment carried out with a group of 30 volunteers. Each person performed six activities wearing the smartphone on the waist and using its embedded accelerometer and gyroscope they collected several measures. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

### Script to tide the raw data

We should create one R script called run_analysis.R that does the following.

#. Merges the training and the test sets to create one data set.
#. Extracts only the measurements on the mean and standard deviation for each measurement.
#. Uses descriptive activity names to name the activities in the data set
#. Appropriately labels the data set with descriptive variable names.
#. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
#. Saves the tidy data set into a txt file

### Review Criteria

We should meet the following criteria.

- The submitted data set is tidy.
- The Github repo contains the required scripts.
- GitHub contains a code book that modifies and updates the available codebooks with the data to indicate all the variables and summaries calculated, along with units, and any other relevant information.
- The README that explains the analysis files is clear and understandable.
- The work submitted for this project is the work of the student who submitted it.

## Prerequisites

These are the prerequisites to run the script to perform the analysis.

- R-3.6.3 or later
- Rstudio version 1.2.5033 or later
- Tidyr package installed
- Dplyr package installed
- Internet connection

## Usage

To perform the analysis do the following steps:

#. Open the project ProgrammingAssignment3.Rproj in RStudio
#. Source the run_analysis.R script
#. Run the function run_analysis() at the Console

## Files

These are the files in the project:

- **README.md** this file

- **CodeBook.md** description of the variables, the data, and any transformations or work performed to clean up the data

- **getdata_projectfiles_UCI HAR Dataset.zip** raw data downloaded as a zip file

- **UCI HAR Dataset** folder containing the raw data unzipped used in this project

- **run_analysis.R** script performing the analysis

- **TidyAvgSummary.txt** final tidy data set generated by the script.  It contains the average of each variable for each subject and each activity 
